### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [restub/PochtaSdk#6]
Hello, your projects has been created successfully, but right after creating a project
You just need to click 'Rebuild' in docfx manager.

![image](https://github.com/restub/PochtaSdk/assets/19374897/e8db35c0-f5ef-433f-978f-93fa65c4754e)

https://www.robiniadocs.com/d/cdeksdk/api/CdekSdk.CdekClient.html
https://www.robiniadocs.com/d/pochtasdk/api/PochtaSdk.html
https://www.robiniadocs.com/d/restub/api/Restub.Authenticator.html

(open pages in incognito mode because of caching)

Regards
Neuroxiq

**Comment by yallie** [comment]
Thanks for the info Marek!
Great API browser by the way 👍
